# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.define :fdb01 do |fdb|
    fdb.vm.box = "Debian6"
    fdb.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", auto_correct: true
    fdb.vm.network "private_network", ip: "192.168.34.0", id: "default-network", type: "dhcp"
  end

  config.vm.define :fdb02 do |fdb|
    fdb.vm.box = "Debian6"
    fdb.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", auto_correct: true
    fdb.vm.network "private_network", ip: "192.168.34.0", id: "default-network", type: "dhcp"
  end

  config.vm.define :fdb03 do |fdb|
    fdb.vm.box = "Debian6"
    fdb.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", auto_correct: true
    fdb.vm.network "private_network", ip: "192.168.34.0", id: "default-network", type: "dhcp"
  end
end
